Fix recent regression with import hooks in blocks (#1369)
This fixes a regression introduced in
https://github.com/com-lihaoyi/Ammonite/pull/1361. This makes the
following work again as expected:
```scala
@ {
    import $ivy.`org.typelevel::cats-kernel:2.6.1`
  }
```

Before the changes here, in Scala 2.x, one gets an error like
```text
cmd0.sc:2: object org.typelevel::cats-kernel:2.6.1 is not a member of package ammonite.$ivy
import $ivy.`org.typelevel::cats-kernel:2.6.1`
       ^
Compilation Failed
```