[Scala3] support extension methods (#1282)
fix: https://github.com/com-lihaoyi/Ammonite/issues/1281

Previously, ammonite REPL couldn't define extension methods
because of the lack of Preprocessor for extension method definition.

```
❯ scala-cli repl --scala 3.1.3 --ammonite
Loading...
Welcome to the Ammonite Repl 2.5.4-11-4f5bf2aa (Scala 3.1.3 Java 17.0.3)
@ extension (foo: Int)
    def bar = foo

-- [E006] Not Found Error: cmd0.sc:1:11 ----------------------------------------
1 |val res0 = extension (foo: Int)
  |           ^^^^^^^^^
  |           Not found: extension
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: cmd0.sc:1:22 ----------------------------------------
1 |val res0 = extension (foo: Int)
  |                      ^^^
  |                      Not found: foo
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: cmd0.sc:2:12 ----------------------------------------
2 |  def bar = foo
  |            ^^^
  |            Not found: foo
  |
  | longer explanation available when compiling with `-explain`
Compilation Failed
```

Now, this is possible to define extension methods in Ammonite REPL.

```
Welcome to the Ammonite Repl 2.5.4-14-dc4c47bc (Scala 3.1.3 Java 1.8.0_302)
@ extension (foo: Int)
    def x = 1
    def y = 1

defined extension methods

@ 100.x
res1: Int = 1
```