Fix line numbers in exceptions for multi-line code blocks (#1361)
## What is changed?
The current Parser ignores whitespaces at the beginning of the code
block, which may result in incorrect line number in an exception
stackTrace:
```
@ {
  
  
  1 / 0
  } 
java.lang.ArithmeticException: / by zero
  ammonite.$sess.cmd0$.<init>(cmd0.sc:1)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc)
```

This PR changes it so the result will be
```
@ { 
  
  
  1 / 0
  } 
java.lang.ArithmeticException: / by zero
  ammonite.$sess.cmd0$.<init>(cmd0.sc:4)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc)

```
(line number is 4 instead of 1)

This it done by introducing a new parser which does not ignore leading
whitespaces


Please note that it changes this only for Scala 2. Scala 3 impl has a
different parsing logics which I didn't have time to dive into yet
## How is it tested?
New tests in `FailureTests` checking line numbers